routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Ticket;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;



Route::get('/logout' , 'AdminController@logout')->name('logout');
Route::middleware(['auth:web'])->group(function () {
    Route::as('panel.')->prefix('/panel')->group(function () {

        Route::get('/', 'AdminController@index');
        Route::post('/edit_profile/{user}' ,'AdminController@edit_profile');
        Route::post('/change_pass/{user}' ,'AdminController@change_pass');
        Route::get('/home', 'AdminController@index')->name('home');

        Route::as('category.')->prefix('/category')->group(function () {
            Route::resource('/', 'CategoryController');
            Route::get('/index', 'CategoryController@index')->name('cat_index');
            Route::get('/create', 'CategoryController@create')->name('cat_create');
            Route::post('/edit/{category}', 'CategoryController@edit');
            Route::post('/store/{category}', 'CategoryController@store');
            Route::get('/delete/{category}', 'CategoryController@destroy');

        });

        Route::as('city.')->prefix('/city')->group(function () {
            Route::resource('/', 'CityController');
            Route::get('/index', 'CityController@index')->name('city_index');
            Route::get('/create', 'CityController@create')->name('city_create');
            Route::post('/edit/{city}', 'CityController@edit');
            Route::post('/store/{city}', 'CityController@store');
            Route::get('/delete/{city}', 'CityController@destroy');

        });

        Route::as('location.')->prefix('/location')->group(function () {
            Route::resource('/', 'LocationController');
            Route::get('/index', 'LocationController@index')->name('loc_index');
            Route::get('/create', 'LocationController@create')->name('loc_create');
            Route::post('/edit/{location}', 'LocationController@edit');
            Route::post('/store/{location}', 'LocationController@store');
            Route::get('/delete/{location}', 'LocationController@destroy');

        });

        Route::as('estate.')->prefix('/estate')->group(function () {
            Route::resource('/', 'EstateController');
            Route::get('/index', 'EstateController@index')->name('est_index');
            Route::get('/create', 'EstateController@create')->name('est_create');
            Route::get('/search', 'EstateController@search')->name('est_search');
            Route::post('/edit/{estate}', 'EstateController@edit');
            Route::post('/store/{estate}', 'EstateController@store');
            Route::get('/delete/{estate}', 'EstateController@destroy');
        });


        Route::as('house.')->prefix('/house')->group(function () {
            Route::resource('/', 'HouseController');
            Route::get('/house', 'HouseController@index')->name('est_index');
            Route::post('/edit/{estate}', 'HouseController@edit');
            Route::get('/delete/{estate}', 'HouseController@destroy');
        });


        Route::as('apartment.')->prefix('/apartment')->group(function () {
            Route::resource('/', 'ApartmentController');
            Route::get('/apartment', 'ApartmentController@index')->name('est_index');
            Route::post('/edit/{estate}', 'ApartmentController@edit');
            Route::get('/delete/{estate}', 'ApartmentController@destroy');
        });


        Route::as('agriculture.')->prefix('/agriculture')->group(function () {
            Route::resource('/', 'AgricultureController');
            Route::get('/agriculture', 'AgricultureController@index')->name('est_index');
            Route::post('/edit/{estate}', 'AgricultureController@edit');
            Route::get('/delete/{estate}', 'AgricultureController@destroy');
        });


        Route::as('earth.')->prefix('/earth')->group(function () {
            Route::resource('/', 'EarthController');
            Route::get('/earth', 'EarthController@index')->name('est_index');
            Route::post('/edit/{estate}', 'EarthController@edit');
            Route::get('/delete/{estate}', 'EarthController@destroy');
        });


        Route::as('commercial.')->prefix('/commercial')->group(function () {
            Route::resource('/', 'CommercialController');
            Route::get('/commercial', 'CommercialController@index')->name('est_index');
            Route::post('/edit/{estate}', 'CommercialController@edit');
            Route::get('/delete/{estate}', 'CommercialController@destroy');
        });

        Route::as('order.')->prefix('/order')->group(function () {
            Route::get('/', 'OrderController@index')->name('index');
            Route::post('/store', 'OrderController@store');
            Route::post('/edit/{order}', 'OrderController@edit');
            Route::post('/delete_order/{order}', 'OrderController@delete_order');
        });

        Route::as('ladder.')->prefix('/ladder')->group(function () {
            Route::get('/', 'LadderController@index')->name('index');
            Route::post('/edit/{estate}', 'LadderController@edit');
        });


        Route::as('ticket.')->prefix('/ticket')->group(function () {
            Route::resource('/', 'TicketController');
            Route::get('/p_index', 'TicketController@panel_index')->name('panel_index');
            Route::post('/send_reply/{ticket}', 'TicketController@send_reply')->name('send_reply');
            Route::get('/delete_ticket/{ticket}', 'TicketController@delete_ticket')->name('delete_ticket');

        });



        Route::as('notice.')->prefix('/notice')->group(function () {
            Route::resource('/', 'NoticeController');
            Route::post('/store', 'NoticeController@store')->name('store_not');
        });

    });

});

Route:: get('/', 'HomeController@index');
Route:: post('/estates/order', 'OrderController@store')->name('order.store');
Route:: get('/estates', 'EstateController@indexView');
Route:: get('/house', 'HouseController@indexView');
Route:: get('/apartment', 'ApartmentController@indexView');
Route:: get('/agriculture', 'AgricultureController@indexView');
Route:: get('/commercial', 'CommercialController@indexView');
Route:: get('/earth', 'EarthController@indexView');
Route:: post('/contactus/ticket', 'TicketController@store')->name('ticket.store');
Route:: get('/estates/{estate}', 'EstateController@singleView');
Route:: get('/contactus', 'ContactusController@index');
Route:: get('/aboutus', 'AboutusController@index');




Auth::routes();

resources/views/layout/panel/master.blade.php
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="fontiran.com:license" content="Y68A9">
    <link rel="icon" href="{{asset('assets/images/favicon.ico')}}" type="image/ico"/>
    <title>پنل مدیریت  </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap.rtl.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/fontawesome.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/nprogress.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap-progressbar-3.3.4.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/green.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/daterangepicker.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/css/custom.min.css')}}">
    <script src="{{asset('assets/js/customize-widgets.js')}}"></script>
</head>
<!-- /header content -->
<body class="nav-md .">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col hidden-print">
            @include('layout.panel.menu')
        </div>

        <!-- top navigation -->
        <div class="top_nav hidden-print">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
{{--                                <img src="{{asset('assets/images/img.jpg')}}" alt="">مرتضی کریمی--}}
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">

                                <li><a href="/logout"><i class="fa fa-sign-out pull-right"></i> خروج</a></li>
                            </ul>
                        </li>

                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->
        <!-- /header content -->

        <!-- page content -->
@yield('content')
        <!-- /page content -->

        <!-- footer content -->
        <footer class="hidden-print">
            <div class="pull-left">
                {{--Gentelella - قالب پنل مدیریت بوت استرپ <a href="https://colorlib.com">Colorlib</a> | پارسی شده توسط <a--}}
                        {{--href="https://morteza-karimi.ir">مرتضی کریمی</a>--}}
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>
<div id="lock_screen">
    <table>
        <tr>
            <td>
                <div class="clock"></div>
                <span class="unlock">
                    <span class="fa-stack fa-5x">
                      <i class="fa fa-square-o fa-stack-2x fa-inverse"></i>
                      <i id="icon_lock" class="fa fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
                </span>
            </td>
        </tr>
    </table>
</div>
<!-- jQuery -->

<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/fastclick.js')}}"></script>
<script src="{{asset('assets/js/nprogress.js')}}"></script>
<script src="{{asset('assets/js/bootstrap-progressbar.min.js')}}"></script>
<script src="{{asset('assets/js/icheck.min.js')}}"></script>
<script src="{{asset('assets/js/moment.min.js')}}"></script>
<script src="{{asset('assets/js/daterangepicker.js')}}"></script>
<script src="{{asset('assets/js/Chart.min.js')}}"></script>
<script src="{{asset('assets/js/jquery.sparkline.min.js')}}"></script>
<script src="{{asset('assets/js/gauge.min.js')}}"></script>
<script src="{{asset('assets/js/skycons.js')}}"></script>
<script src="{{asset('assets/js/jquery.flot.js')}}"></script>
<script src="{{asset('assets/js/jquery.flot.pie.js')}}"></script>
<script src="{{asset('assets/js/jquery.flot.time.js')}}"></script>
<script src="{{asset('assets/js/jquery.flot.stack.js')}}"></script>
<script src="{{asset('assets/js/jquery.flot.resize.js')}}"></script>
<script src="{{asset('assets/js/jquery.flot.orderBars.js')}}"></script>
<script src="{{asset('assets/js/jquery.flot.spline.min.js')}}"></script>
<script src="{{asset('assets/js/curvedLines.js')}}"></script>
<script src="{{asset('assets/js/date.min.js')}}"></script>
<script src="{{asset('assets/js/jquery.vmap.js')}}"></script>
<script src="{{asset('assets/js/jquery.vmap.world.js')}}"></script>
<script src="{{asset('assets/js/jquery.vmap.sampledata.js')}}"></script>
<script src="{{asset('assets/js/custom.min.js')}}"></script>



</body>
</html>

resources/views/layout/panel/menu.blade.php
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="#" class="site_title"><i class="fa fa-paw"></i> <span>پنل مدیریت </span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
        {{--<div class="profile_pic">--}}
            {{--<img src="#" alt="..." class="img-circle profile_img">--}}
        {{--</div>--}}
        <div class="profile_info">
            <span>خوش اومدی فرشاد</span>
            <br/>
            {{--{{\Illuminate\Support\Facades\Auth::user()->f_name}}--}}

        </div>
    </div>
    <!-- /menu profile quick info -->

    <br/>

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            {{--admin--}}
            <h3>پنل مدیریت</h3>
            <ul class="nav side-menu">
                <li><a href="/panel/"><i class="fa fa-windows"></i> داشبورد </a>
                </li>


                <li><a><i class="fa fa-circle-o"></i> املاک<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
{{--                        <li><a href="{{route('panel.estate.est_index')}}">مدیریت املاک</a></li>--}}
                        <li><a href="{{route('panel.estate.est_create')}}">ثبت ملک جدید </a>
                        </li>
                        <li><a href="{{route('panel.estate.est_search')}}">جستجوی ملک</a>
                        </li>
                    </ul>

                </li>



                <li><a><i class="fa fa-home"></i> خانه و ویلا<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.house.est_index')}}">مدیریت املاک خانه و ویلایی</a></li>
{{--                        <li><a href="#">ثبت خانه و ویلای جدید </a>--}}
                        </li>
                    </ul>
                </li>



                <li><a><i class="fa fa-building-o"></i> آپارتمان<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.apartment.est_index')}}">مدیریت املاک آپارتمانی</a></li>
{{--                        <li><a href="#">ثبت آپارتمان جدید </a>--}}
                        </li>
                    </ul>
                </li>


                <li><a><i class="fa fa-tree"></i> کشاورزی و باغ<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.agriculture.est_index')}}">مدیریت املاک کشاورزی و باغ</a></li>
{{--                        <li><a href="#">ثبت زمین کشاورزی و باغ جدید </a>--}}
                        </li>
                    </ul>
                </li>


                <li><a><i class="fa fa-map"></i> زمین<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.earth.est_index')}}">مدیریت املاک زمین</a></li>
{{--                        <li><a href="#">ثبت زمین جدید </a>--}}
                        </li>
                    </ul>
                </li>


                <li><a><i class="fa fa-wrench"></i> تجاری و صنعتی<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.commercial.est_index')}}">مدیریت املاک تجاری و صنعتی</a></li>
{{--                        <li><a href="#">ثبت ملک تجاری و صنعتی جدید </a>--}}
                        </li>
                    </ul>
                </li>




                <li><a><i class="fa fa-group"></i> دسته بندی<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.category.cat_index')}}">مدیریت دسته بندی</a></li>
                        <li><a href="{{route('panel.category.cat_create')}}">ثبت دسته جدید</a>
                        </li>
                    </ul>
                </li>



                <li><a><i class="fa fa-map-o"></i> شهرها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.city.city_index')}}">مدیریت شهرها</a></li>
                        <li><a href="{{route('panel.city.city_create')}}">ثبت شهر جدید</a>
                        </li>
                    </ul>
                </li>



                <li><a><i class="fa fa-map-marker"></i> منطقه<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu" style="display: none;">
                        <li><a href="{{route('panel.location.loc_index')}}">مدیریت منطقه</a></li>
                        <li><a href="{{route('panel.location.loc_create')}}">ثبت منطقه جدید</a>
                        </li>
                    </ul>
                </li>


                <li><a href="{{route('panel.ladder.index')}}"><i class="fa fa-arrow-circle-up"></i>نردبان آگهی</a>
                </li>


                <li><a href="{{route('panel.order.index')}}"><i class="fa fa-briefcase"></i>درخواست های کارشناسی ملک</a>
                </li>






{{--                <li><a><i class="fa fa-picture-o"></i> گالری تصاویر<span class="fa fa-chevron-down"></span></a>--}}
{{--                    <ul class="nav child_menu" style="display: none;">--}}
{{--                        <li><a href="{{route('panel.gallery.index')}}">مدیریت</a></li>--}}
{{--                        --}}{{--<li><a href="#">مشاهده سوابق مالی</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

                {{--<li><a><i class="fa fa-group"></i> اطلاعیه ها<span class="fa fa-chevron-down"></span></a>--}}
                    {{--<ul class="nav child_menu" style="display: none;">--}}
                        {{--<li><a href="{{route('panel.notice.index')}}">نمایش اطلاعیه ها</a></li>--}}
                        {{--<li><a href="{{route('panel.notice.create')}}">ثبت اطلاعیه جدید </a></li>--}}
                        {{--<li><a href="#">مشاهده سوابق مالی</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}

                {{--<li><a><i class="fa fa-group"></i> همکاران<span class="fa fa-chevron-down"></span></a>--}}
                    {{--<ul class="nav child_menu" style="display: none;">--}}
                        {{--<li><a href="{{route('panel.teammate.indextm')}}">نمایش همکاران</a></li>--}}
                        {{--<li><a href="{{route('panel.teammate.createtm')}}">ثبت همکار جدید </a></li>--}}
                        {{--<li><a href="#">مشاهده سوابق مالی</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}

                {{--<li><a><i class="fa fa-group"></i> گواهینامه ها<span class="fa fa-chevron-down"></span></a>--}}
                    {{--<ul class="nav child_menu" style="display: none;">--}}
                        {{--<li><a href="{{route('panel.certificate.indexcer')}}">نمایش گواهینامه ها</a></li>--}}
                        {{--<li><a href="{{route('panel.certificate.createcer')}}">ثبت گواهینامه جدید </a></li>--}}
                        {{--<li><a href="#">مشاهده سوابق مالی</a></li>--}}
                    {{--</ul>--}}
                {{--</li>--}}

                {{--<li><a href="{{route('panel.order.index')}}"><i class="fa fa-paper-plane-o"></i> سفارشات</a>--}}
                {{--</li>--}}
                <li><a href="{{route('panel.ticket.panel_index')}}"><i class="fa fa-paper-plane-o"></i> پشتیبانی</a>
                </li>



            </ul>
        </div>

    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        {{--<a data-toggle="tooltip" data-placement="top" title="تنظیمات">--}}
        {{--<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>--}}
        {{--</a>--}}
        <a data-toggle="tooltip" data-placement="top" title="تمام صفحه" onclick="toggleFullScreen();">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="قفل" class="lock_btn">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="خروج">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
</div>